django_allauth/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('allauth.urls')),
    url(r'accounts/', include('users.urls', namespace='users')),
]

users/urls.py
# -*- coding: utf-8 -*-
# @Time    : 19-1-10 下午2:11
# @Author  : Nick
# @Email   : haijun0422@126.com
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from .views import profile, profile_update

app_name = 'users'
urlpatterns = [
    url(r'^profile/', profile, name='profile'),
    url(r'^profile_update/', profile_update, name='profile_update')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    arg = models.CharField(max_length=128, verbose_name='机构')
    tel = models.CharField(max_length=15, verbose_name='电话')
    mod_date = models.DateTimeField(auto_now=True, verbose_name='修改日期')

    class Meta:
        db_table = 'user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user

users/forms.py
# -*- coding: utf-8 -*-
# @Time    : 19-1-10 下午2:30
# @Author  : Nick
# @Email   : haijun0422@126.com
# @File    : forms.py
# @Software: PyCharm

from django import forms
from .models import UserProfile


class ProfileForm(forms.Form):
    first_name = forms.CharField(label='名', max_length=50, required=False)
    last_name = forms.CharField(label='姓', max_length=50, required=False)
    org = forms.CharField(label='机构', max_length=50, required=False)
    telephone = forms.CharField(label='电话', max_length=50, required=False)


class SignupForm(forms.Form):
    def signup(self, request, user):
        user_profile = UserProfile()
        user_profile.user = user
        user.save()
        user_profile.save()

users/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import UserProfile
from .forms import ProfileForm, SignupForm


@login_required
def profile(request):
    user = request.user
    return render(request, 'profile.html', {'user': user})


@login_required
def profile_update(request):
    user = request.user
    user_profile = get_object_or_404(UserProfile, user=user)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            user_profile.org = form.cleaned_data['org']
            user_profile.tel = form.cleaned_data['telephone']
            user_profile.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            defaulte_data = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'org': user_profile.org,
                'telephone': user_profile.tel
            }
            form = ProfileForm(defaulte_data)
    return render(request, 'profile_date.html', {'user': user, 'form': form})

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
<a href="{% url 'users:profile_update' %}">Update Profile</a> | <a href="{% url 'account_email' %}">Manage Email</a>  | <a href="{% url 'account_change_password' %}">Change Password</a> |
<a href="{% url 'account_logout' %}">Logout</a>
{% endif %}
<p>Welcome, {{ user.username }}.</p>


<h2>My Profile</h2>
<ul>
    <li>First Name: {{ user.first_name }} </li>
    <li>Last Name: {{ user.last_name }} </li>
    <li>Organization: {{ user_profile.org }} </li>
    <li>Telephone: {{ user_profile.telephone }} </li>
</ul>


</body>
</html>

templates/profile_date.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
<a href="{% url 'myaccount:profile_update' %}">Update Profile</a> | <a href="{% url 'account_email' %}">Manage Email</a>  | <a href="{% url 'account_change_password' %}">Change Password</a> |
<a href="{% url 'account_logout' %}">Logout</a>
{% endif %}
<h2>Update My Profile</h2>

<div class="form-wrapper">
   <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
           <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
           </div>
        {% endfor %}
      <div class="button-wrapper submit">
         <input type="submit" value="Update" />
      </div>
   </form>
</div>

</body>
</html>